### ISSUE TITLE
christiangirl41@gmail.com flagged

### ISSUE THREAD

**Issue by christiangirl41** [RocketChat/botkit-rocketchat-connector#1]
Please help me fix my account privacy

**Comment by ElijahChase** [comment]
I was fucking Flagged too. Thats stupid! I did _nothing_ WRONG!

**Comment by christiangirl41** [comment]
❤️💱

**Comment by timkinnane** [comment]
This is a placeholder repo for a project that has not yet begun and has no active users. I'm not sure if this is spam or just posting to the wrong place, but it's definitely not a relevant issue.
