### ISSUE TITLE
[BUG]  should support channel_join message type

### ISSUE THREAD

**Issue by ear-dev** [RocketChat/botkit-rocketchat-connector#5]
Currently the `incomingMessage` is using `type: messageSource` seen here: https://github.com/RocketChat/botkit-rocketchat-connector/blob/develop/RocketChatBot.js#L43
 
and in bot.js this type is used to to trigger the controller.on() events here:  https://github.com/RocketChat/botkit-starter-rocketchat/blob/develop/bot.js#L55

I was looking at onboarding messages and I noticed that when a user joins or leaves a channel a message is sent to the bot from RC that includes a field `t` which can at times be `uj` or `ul`, "user joined" or "user left" respectively.

By parsing for the field `t` when it exists, and populating `type: "channel_join"` in the `uj` case, I was able to trigger an onboarding event using the controller.on("channel_join", ...) event trigger.  Example here: https://botkit.ai/docs/core.html#controlleron

I'm not sure if this is the best way to do onboarding, but do you think we'll want to enhance the connector to be able to trigger on other events besides just using the messageSource?

**Comment by Sing-Li** [comment]
> I was looking at onboarding messages and I noticed that when a user joins or leaves a channel a message is sent to the bot from RC that includes a field t which can at times be uj or ul, "user joined" or "user left" respectively.
> 
> By parsing for the field t when it exists, and populating type: "channel_join" in the uj case, I was able to trigger an onboarding event using the controller.on("channel_join", ...) event trigger. Example here: https://botkit.ai/docs/core.html#controlleron
> 

We definitely should do this in the adapter.  @diegodorgam  and @arthurTemporim  can we add this mapping in the adapter asap.    This is basic feature that should have been supported - our hubot adapter has it for a long time.

**Comment by timkinnane** [comment]
Here is the Hubot handling of enter/leave types:
https://github.com/RocketChat/hubot-rocketchat/blob/930d085472bb9afa122721fa1b0bec59a783b86b/index.js#L102-L111

You just need to copy that, creating whatever the botkit equivalent is for the framework's enter/leave event.

**Comment by timkinnane** [comment]
SDK tests added and passing, it is definitely calling the `respondToMessages` callback with enter/leave/invite (`uj`, `ul`, `au`) message types.

https://github.com/RocketChat/Rocket.Chat.js.SDK/commit/2ceb4c321fea6dbd324e606fb792720e1255bb39

I just can't write a unit test for the `uj` type because there's no API endpoint to trigger it.
